### ISSUE TITLE
line stroke smoothing 

### ISSUE THREAD

**Issue by musahinist** [RomanBase/hand_signature#1]
Thank you for doing a great job. I have a request can you apply the [stroke smoothing](http://jsfiddle.net/xup4T/) algorithm to SignatureDrawType.line

**Comment by RomanBase** [comment]
Hi, from now SignatureDrawType.line using same smoothing algorithm as 'shape' and 'arc' draw types.

You can play with 'threshold' and 'smoothRatio' params of 'HandSignatureControl ' to create more smooth or more accurate line.

Also there is a plan to test/add another algorithms, but this needs some time.
You can of course make own algorithm and contribute your solution, thanks.
