### ISSUE TITLE
Quality issues on web

### ISSUE THREAD

**Issue by Uni2K** [RomanBase/hand_signature#16]
The image quality is not good in flutter web. To be fair, similar libraries have the same issue. It seems to be something fundamental, maybe you can look into it.
This is how it looks:
![issue](https://user-images.githubusercontent.com/20185223/119956677-a2fc0f80-bfa1-11eb-88b5-65a6f98065c7.PNG)

The settings are: 
threshold: 0.01,
smoothRatio: 1,
velocityRange: 5.2,

Its really impossible to make it look better, the above mentioned settings are the best thing I was able to find.
Smoothing has a very small effect on the result, maybe this is related to the issue. It makes no big difference whether smoothing is 0.01 or 1.

**Comment by RomanBase** [comment]
Hey this seems like problem with target device or maybe performance issues..

Try to set larger ``threshold``, because with 0.01 there is no place for smoothing. Minimal should be 2.0 and on low devices this value can be even larger.
