### ISSUE TITLE
Cannot drawing signatures inside SingleChildScrollView

### ISSUE THREAD

**Issue by leewonghao** [RomanBase/hand_signature#2]
I have a code:

```
child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.start,
              children: <Widget>[
                HtmlWidget(_formatHTMLRender(html)),
                Container(
                  height: 300,
                  width: double.infinity,
                  color: Colors.white,
                  child: HandSignaturePainterView(
                    control: control,
                    type: SignatureDrawType.shape,
                    color: Colors.cyan,
                  ),
                ),
              ],
            )
          )
```

But I can't draw when scroll page. Please help me. Thanks

**Comment by RomanBase** [comment]
Hi, I think there is no simple solution.
Problem is, that view using PanGestureRecognizer and parent ScrollView will handle all touch inputs..

Simplest solution is to open HandSignatureView in popup or in new page (draw area is much bigger and it's comfortable for user to draw signature).

**Comment by leewonghao** [comment]
> Hi, I think there is no simple solution.
> Problem is, that view using PanGestureRecognizer and parent ScrollView will handle all touch inputs..
> 
> Simplest solution is to open HandSignatureView in popup or in new page (draw area is much bigger and it's comfortable for user to draw signature).

Hi, thanks for your reply.
But I found another solution without open a new page or signature in a popup.

**Comment by tajaouart** [comment]
> > Hi, I think there is no simple solution.
> > Problem is, that view using PanGestureRecognizer and parent ScrollView will handle all touch inputs..
> > Simplest solution is to open HandSignatureView in popup or in new page (draw area is much bigger and it's comfortable for user to draw signature).
> 
> Hi, thanks for your reply.
> But I found another solution without open a new page or signature in a popup.

Hiii Lee,
Can you please tell me the solution you found in order to be able to draw inside a scrollView ?
Thanks in advance

**Comment by jomiplaz** [comment]
Same problem in version 2.1.0

**Comment by RomanBase** [comment]
Hey, drawing in scroll view is not fully supported yet. You can find workaround in example project [(scroll_test)](https://github.com/RomanBase/hand_signature/blob/master/example/lib/scroll_test.dart).

We are still looking for better solution.. maybe `Focus` based, but it's not fully tested yet..

**Comment by jomiplaz** [comment]
> Hey, drawing in scroll view is not fully supported yet. You can find workaround in example project [(scroll_test)](https://github.com/RomanBase/hand_signature/blob/master/example/lib/scroll_test.dart).
> 
> We are still looking for better solution.. maybe `Focus` based, but it's not fully tested yet..

Hi, thanks for your reply.
But the problem is that in version 2.0.0 it worked fine.

**Comment by jomiplaz** [comment]
Hi, I found that if the widget is wrapped with GestureDetector and `onVerticalDragUpdate: (_) {},` it works.
