### ISSUE TITLE
Null Check for .toImage()

### ISSUE THREAD

**Issue by MorosophDude** [RomanBase/hand_signature#20]
Turns out null check is missing in controller.toImage(...) resulting in 
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0

Adding 
`    if (!isFilled) {
      return null;
    }` 
In **signature_control.dart  [Line 1104]** , should do the job

It actually is done in .toSvg() function  in same file - **signature_control.dart  [Line 872-874]**

### If Interested in replicated this issue
Step 1: Fork the official example from https://github.com/RomanBase/hand_signature/tree/master/example
Step 2: Build and Run it
Step 3: Without drawing anything on canvas press 'export' button
 OR, - Draw something, press 'export', press 'clear', and then press 'export' again
Step 4: Observer the debug console

**Comment by RomanBase** [comment]
Thanks for report. This minor issue will be solved in release `2.1.1`.

**Comment by MorosophDude** [comment]
Glad, I could help.
