### ISSUE TITLE
Implementation of toMap / fromMap methods for saving the state

### ISSUE THREAD

**Issue by alifurkanbudak** [RomanBase/hand_signature#25]
Currently, there are only image / SVG exports but it would be nice to save and reinitialize the current state of the signature so we can edit later.
I implemented this and opened a PR.

**Comment by RomanBase** [comment]
Hey, not a bad idea, but I have 2 complains:

1. Isn't possible to recreate List of `CubicPath`s from `svg` file with `SvgParser` [(flutter_svg)](https://pub.dev/packages/flutter_svg)? We will lose control settings and velocity, but do we need them so much ?

2. Map/Json is not too effective for storing large data sets (like vertices) and you are saving a lot of unnecessary fields. I thing it's enough to store just `OffsetPoint`s and control settings.

It will be a little bit more work during Import, but much cleaner and efficient solution.

**Comment by alifurkanbudak** [comment]
I couldn't figure out a way to initialize `CubicArc`s from `CubicLine`s.  Because you need to know if you added a line using `_addLine` or `_addDot`. Even if you figure it out, you still need `_currentVelocity` and `_currentSize` which you don't have access to anymore.

**Comment by RomanBase** [comment]
I just created simple test under [signature_control_test.dart](https://github.com/RomanBase/hand_signature/blob/master/test/signature_control_test.dart) to check if is possible import signature only from `OffsetPoint`s and it's doable :)

Everything you mentioned is possible to calculate just from `x` `y` and `timestamp`, but you need to mimic drawing process for every `CubicLine`:  `begin` -> `add` -> `end`.

Just check individual tests and you will see how it's done. I created this tests in rush, so maybe it's not nicest code, but can be inspiration for production version..

**Comment by alifurkanbudak** [comment]
Thank you for the example. That really helped. I created a new PR.
