### ISSUE TITLE
Some Future Requests

### ISSUE THREAD

**Issue by furkansarihan** [RomanBase/hand_signature#3]
Hello, I am planning to add these;

- Be able to change controller properties while drawing. (width, color)
- Basic undo functionality.

Any toughts? Thanks.

**Comment by RomanBase** [comment]
Hi, purpose of this widget is to draw signature. So dynamic width or color change don't make much sense.. And you can change these properties during export.

Undo can be implemented easily and I will think about it. But again, it's not something you commonly do.

**Comment by furkansarihan** [comment]
Sorry, I should have been mention that I am planning to use this package for simple drawing over images just like we see in common photo editors.

So, Do you suggest creating a new package for different purpose than drawing signature?

### Update!

I moved global draw configurations to CubicPath object. So each path is drawable with it's configs.

Watch it in action: [**video**](https://streamable.com/ici1ye)

It includes minor design changes.
It is up to you to merging them into original package.
I can create a PR after testing the export functions.

**Comment by RomanBase** [comment]
Hi, sorry for late answer..

It totally depends on how complex your drawings could be..
Your video looks good so far and I think it was pretty easy to update.

Currently there is no caching, so it can cause some performance issues. But again, to cache finished lines to separate layer is not so dramatic update library.

What can be problem is zoom/drag/pan functionality.
Another problem are brushes.

If you want to draw just lines, this library and your update can be good start.
Also I can see some jags on drawn lines so smoothing algorithm maybe don't work well in your scenario..
