### ISSUE TITLE
Compatibility with flutter_svg:^2.0.0

### ISSUE THREAD

**Issue by quaaantumdev** [RomanBase/hand_signature#33]
The package is currently stuck at some 1.0.* version of ```flutter_svg``` and there is a 2.0.0+ version available. I created a pull request for the changes required. The pull request also contains some information about the changes done:

Pull request with additional information here --> https://github.com/RomanBase/hand_signature/pull/32

Would appreciate it being merged and released on a new version number. 

Thanks for the great work with the package @RomanBase!

**Comment by RomanBase** [comment]
Because in PR [#32](https://github.com/RomanBase/hand_signature/pull/32) is `HandSignatureView` technically just wrapper around `SvgPicture`, I decided that in version `3.0.0` will be completely removed dependency on `flutter_svg` and `HandSignatureView` removed.
