### ISSUE TITLE
how to draw dash path

### ISSUE THREAD

**Issue by ntvsp** [RomanBase/hand_signature#34]
`case SignatureDrawType.dot:
        final paint = dashPaint;
        for (var path in paths) {
          paint.strokeWidth = width;
          if (path.isFilled) {
            canvas.drawPath(
                dashPath(PathUtil.toLinePath(path.lines),
                    dashArray: CircularIntervalList([
                      10,
                    ])),
                paint);
          }
        }`

i cant export to image, toLinePath(path.lines), path.lines is null?

**Comment by RomanBase** [comment]
Hey, please can you attach full example and provide more description about it ?
