### ISSUE TITLE
toSvg with wrapSignature cuts the signature

### ISSUE THREAD

**Issue by alexgarbarev** [RomanBase/hand_signature#35]
Hello and thank you for wonderful library!

I'd like to raise on minor problem I faced with. 
Sometimes, when I try to export signature `toSvg` using following params:
```dart
final control = HandSignatureControl();
...
HandSignature(
  control: control,
  width: 2.0,
  maxWidth: 5.0,
)
...      
final svg = control.toSvg(
  wrapSignature: true,
);
```
I see that the signature gets cutted. I guess it might be related to line width or something. 
Please see attached screenshots:
Actual signature (inside HandSignature)
<img width="707" alt="Screenshot 2023-02-19 at 14 34 09" src="https://user-images.githubusercontent.com/2268687/219933289-1a8c10d1-c6d6-4650-bace-a2f2d6152c8b.png">
Exported to svg:
<img width="322" alt="Screenshot 2023-02-19 at 14 34 12" src="https://user-images.githubusercontent.com/2268687/219933310-ff117264-cad7-4a29-aff0-09a95963e5a5.png">
Another example of cropped signature (In svg format):
![Signature](https://user-images.githubusercontent.com/2268687/219933325-fdd31bbf-aed6-48f8-a9f1-429694de871a.svg)

Thanks in advance for any advice :)

**Comment by ZdenekKrcal** [comment]
I have same problem, I always get cutted signature with option:

```dart
final svg = control.toSvg(
  wrapSignature: true,
);
```

**Comment by RomanBase** [comment]
Hey, `wrapSignature` has been redesigned to `fit` property to better correspond with properties of other export options.
There was a problem with rescaling/filling data during export, so bounds of the signature are now extended with `maxStrokeWidth` to better fit visible dimensions.

Please check version `3.0.1`.

**Comment by alexgarbarev** [comment]
Thanks @RomanBase it works much better now!

My only humble suggestion is: avoid breaking public API in one patch change (`3.0.0` -> `3.0.1`) in compliance of semantic versioning: https://semver.org/#spec-item-6. (see items 6 and 7).
Instead we could add `@deprecated` annotation with suggestion to use new property instead. Then remove all deprecation in next major release. That way other developers can plan APIs upgrading.
