### ISSUE TITLE
 error creating image based only on 1 drawn pixel

### ISSUE THREAD

**Issue by gemunet** [RomanBase/hand_signature#36]
There is an error that occurs when instead of drawing a line, you only click to paint a single pixel. then when trying to create the image the method fails, when it should create the image

![Screenshot_1677007419](https://user-images.githubusercontent.com/22581144/220440879-7703d895-3e70-4f5e-bf7a-a1e2c6e4e40d.png)

![Snap 2023-02-21 at 16 26 30](https://user-images.githubusercontent.com/22581144/220440948-4daa01c9-0551-41ba-a3db-ce9ae2d1ab20.png)

**error line**
```dart
var pngImage = await control.toImage();
```

**rest of the code**
```dart
final control = HandSignatureControl(
    threshold: 3.0,
    smoothRatio: 0.65,
    velocityRange: 2.0,
  );

......
                  child: HandSignature(
                    control: control,
                    type: SignatureDrawType.shape,
                  ),
...
```

hand_signature v"3.0.0"

**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Versi¢n 10.0.19044.2604], locale es-CL)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.5)
[√] Android Studio (version 2021.3)
[!] Android Studio (version 4.1)
    X Unable to determine bundled Java version.
[√] VS Code (version 1.75.1)
[√] Connected device (5 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Comment by RomanBase** [comment]
In 1 vertice scenario `PathUtil.bounds` returned zero sized `Rect`. So scalling and then painting failed.
To prevent this issue we added `minSize` attribute.
