### ISSUE TITLE
Error: No named parameter with the name 'kind'

### ISSUE THREAD

**Issue by emersonbarcellos** [RomanBase/hand_signature#37]
Atualizei a versão do Flutter SDK e agora aparece esse aviso. Tentei fazer o dowgrade do `hand_signature` mas não resolve.
`.../AppData/Local/Pub/Cache/hosted/pub.dev/hand_signature-3.0.0/lib/src/signature_view.dart:99:11: Error: No named parameter with the name 'kind'.
          kind: kind,
          ^^^^
Target kernel_snapshot failed: Exception
2

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1153

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by emersonbarcellos** [comment]
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.8.0-14.0.pre.25, on Microsoft Windows [versÆo 10.0.22000.1574], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.75.1)
[√] VS Code, 64-bit edition
[√] Connected device (4 available)
[√] Network resources

• No issues found!`

**Comment by RomanBase** [comment]
Sorry I don't understand, but I guess you reported that `kind` was removed from `GestureRecognizer` in Flutter 3.8.0.
Lib was ported to latest API to resolve this issue.

**Comment by emersonbarcellos** [comment]
Mudei para o `channel stable` e o erro sumiu.
