### ISSUE TITLE
how to import Sign from a base64String

### ISSUE THREAD

**Issue by jaypathak9460** [RomanBase/hand_signature#39]
I have tried all the available methods on internet but i am unable to import sign
senario:-
 i have a form in which user can sign it using web or using mobile app but issue is data is stored in base64string into database 
 i am able to convert signed output to base64 but unable to refill after application restarts or another form will open it basically opens as a blank sign 

expectation:
if user is refilling the form then sign can be reedit if user wants but there is no initdata which i assign

**Comment by RomanBase** [comment]
Hey,  how do you export data (I guess `toImage` and then encoding to base64)?
If you want to save current state you need to export data as Map (json) via `toMap` function. And then you are able to import them back to `HandSignatureControl` via `importData(Map)`.

But you can't import or display raw image with this library.
Typically when you decode base64 string then you need to show image with `Image.memory(Uint8List)` Widget.

**Comment by jaypathak9460** [comment]
yes that how i achieved it but how can i edit this if i dont store this MAP(json) exported by package also i do not have single signature in a same form it can be more than 3-4 so at that time saving both(base64 and json ) will not looks like a good option.

In web i have achieved it by putting same base64 to image into a canvas so user can access it but in this package i did not find any option also i have tried some other packages but they also do not provide this feature, moreover they do not have restore state options so i am finding a way to restore sign from base64 in this package.

**Comment by RomanBase** [comment]
You can restore State only with Vector data = Map `toData` -> `importData`.
There is no way how to restore this kind of data from Raster Image.
So if you want to continue in previous state you need to use Vector data.

This library (and most of others) is just drawing pad (aimed to user signatures) = after you export data to Picture you need to display them via Image Widget.

And again, base64 is just encoding so you need to decode your data first.
