### ISSUE TITLE
Replace assert with null checks

### ISSUE THREAD

**Issue by meandmymonkey7** [RomanBase/hand_signature#42]
Hello, just found out  assert method is only available in debug mode at dart by default : 

https://docs.flutter.dev/testing/build-modes

So any references used in code should be replaced with null checks.

This currently causes an  exception only at release mode, surprisingly we only got this on iOS  : 

Null check operator used on a null value

`#0 HandSignatureControl.alterPath (package:hand_signature/src/signature_control.dart:803) #1 HandSignature.build.. (package:hand_signature/src/signature_view.dart:65) #2 _SingleGestureRecognizer.handleEvent (package:hand_signature/src/signature_view.dart:113) #3 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98) #4 PointerRouter._dispatchEventToRoutes. (package:flutter/src/gestures/pointer_router.dart:143) #5 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625) #6 PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141) #7 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127) #8 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460) #9 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440) #10 RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336) #11 GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395) #12 GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357) #13 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314) #14 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295) #15 _invoke1 (dart:ui/hooks.dart:164) #16 PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361) #17 _dispatchPointerDataPacket (dart:ui/hooks.dart:91)
`

**Comment by RomanBase** [comment]
Hey, can you please provide your Flutter and Dart version - `flutter doctor`.
Thanks.

**Comment by meandmymonkey7** [comment]
I added this bellow but don't think version has anything to do with it. The documentation is clear and assert won't stop code execution at release mode.

We managed to reproduce the issue as follows : 

 "if the user flips the phone from portrait to landscape mode and the opposite, while putting his signature. IOS ONLY"

 I have already applied a fix locally with a null check as proposed and it's working. No more exceptions are received.

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.5.2 22G91 darwin-arm64, locale en-GR)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    ✗ Android SDK file not found: /Users/mac2023/Library/Android/sdk/platforms/android-34/android.jar.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.79.2)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
mac2023s-mini:delivery-iq mac2023$ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.5.2 22G91 darwin-arm64, locale en-GR)
    • Flutter version 3.7.12 on channel stable at /Users/mac2023/develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (8 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at /Users/mac2023/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc2
    ✗ Android SDK file not found: /Users/mac2023/Library/Android/sdk/platforms/android-34/android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.79.2)
    • VS Code at /Users/mac2023/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • 8 plus (mobile)             • 4F65214F-D1DB-408D-B950-F56D4B4D67A0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • iPhone 14 Pro Max (mobile)  • 3AED2137-5C14-4371-872C-4A23F18AF3A0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 119.0.6045.199

[✓] HTTP Host Availability
    • All required HTTP hosts are available
`

**Comment by RomanBase** [comment]
`assert` is just for debug purposes and during build is removed from dart code, so this error is not relevant to assert check.

Your problem refers to null pointer in `SignatureControl.alterPath` - it means that this function is called before `SignatureControl.startPath` or after `SignatureControl.closePath`.

Null pointer is resolved in version `3.0.2`, but still it's weird that alterPath is called before startPath (Maybe bug in GestureRecognizer).

**Comment by meandmymonkey7** [comment]
> `assert` is just for debug purposes and during build is removed from dart code, so this error is not relevant to assert check.
> 
> Your problem refers to null pointer in `SignatureControl.alterPath` - it means that this function is called before `SignatureControl.startPath` or after `SignatureControl.closePath`.
> 
> Null pointer is resolved in version `3.0.2`, but still it's weird that alterPath is called before startPath (Maybe bug in GestureRecognizer).

Ok then if assert was just for debug then it doesn't make sense as you said . From viewing code I thought you had this to interrupt code execution as well (which will happen at debug enviroment with assert) so seeing code made me think this being used like that because you thought it could happen. 

Maybe some state is fired again at screen flip. Which is expected since flutter needs  to draw things again.  I didn't check all of the code but if let's say you set this as null at some initial execution what if this part is fired again?

**Comment by RomanBase** [comment]
Problem is that some devices (maybe just iPhone/iPad) holds pointer active during screen rotation.
During this flip a `notifyDimension` function is called to resize current `paths`. So to resize active path we firstly need to close it with `closePath`. And that's the reason why null pointer was fired.
I will fill new issue..
