### ISSUE TITLE
Add undo feature

### ISSUE THREAD

**Issue by Yaronkr** [RomanBase/hand_signature#48]
By implementing the following code, I was able to implement undo feature. Just a suggestion to add to the package. 

Code: 

   Map<String, dynamic> currentState = _controller.toMap();
              
              if (currentState['paths'].isNotEmpty) {
                _controller.clear();
                currentState['paths'].removeLast();

                _controller.importData(currentState);
              }

**Comment by RomanBase** [comment]
Hey, please check `SignatureControl.stepBack` function.
