### ISSUE TITLE
PictureStream 

### ISSUE THREAD

**Issue by marcoedomingos** [RomanBase/hand_signature#6]
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found. class PictureStream with DiagnosticableMixin {

Is occurring this error when i'm trying to build the apk, probably you are using a deprecated class in the flutter_svg package, maybe can be solved by updating the package to flutter_svg: ^0.19.0.

Thank you for the attention.

**Comment by RomanBase** [comment]
Hi, `flutter_svg` version is se to `any`.
So calling `flutter pub get` or `flutter pub upgrade` should update this library to match version in your pubspec.yaml or to latest version..
