### ISSUE TITLE
New feature: base64 method

### ISSUE THREAD

**Issue by c0c4i** [RomanBase/hand_signature#7]
Hello, I'm trying to convert signature to base64 but from toImage() I'm not able to convert to base64.
I don't know if there is a workaround that permit that.
Thank you 👍🏻

**Comment by RomanBase** [comment]
Hi, image is returned as `ByteData` so you need to get raw data firstly -> `ByteData.buffer.asUint8List()`, then u can use `dart:convert` package to convert to base64 string.

A little example here:
``` dart
import 'dart:convert';

final control = HandSignatureControl();
final image = await control.getImage();
final rawData = image.buffer.asUint8List();

final base64String = base64Encode(rawData);
```

**Comment by c0c4i** [comment]
Thank you a lot for the solution 👍🏻
