### ISSUE TITLE
onChange function

### ISSUE THREAD

**Issue by c0c4i** [RomanBase/hand_signature#8]
Is it possible to control every time the status of signature? 
I know there is isSigned method but i can't enable/disable button during the write of signature because the check on control became only at the start.
Thank you

**Comment by RomanBase** [comment]
Hi, `HandSignatureControl` is `ChangeNotifier` so you can `addListener` and check for changes.

For your needs you can check `isFilled` and `hasActivePath` properties.

```dart
final control = HandSignatureControl();

control.addListener((){
  final isSomethingOnCanvas = control.isFilled || control.hasActivePath;
});
```

`hasActivePath` - [true] user currently drawing.
`isFilled` - [true] there is one or more finished parts of signature.
